/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gwenod.visa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Visa service. Represents a row in the &quot;_visa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.gwenod.visa.model.impl.VisaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.gwenod.visa.model.impl.VisaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Visa
 * @generated
 */
@ProviderType
public interface VisaModel
	extends BaseModel<Visa>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visa model instance should use the {@link Visa} interface instead.
	 */

	/**
	 * Returns the primary key of this visa.
	 *
	 * @return the primary key of this visa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visa.
	 *
	 * @param primaryKey the primary key of this visa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this visa.
	 *
	 * @return the uuid of this visa
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this visa.
	 *
	 * @param uuid the uuid of this visa
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the visa ID of this visa.
	 *
	 * @return the visa ID of this visa
	 */
	public long getVisaId();

	/**
	 * Sets the visa ID of this visa.
	 *
	 * @param visaId the visa ID of this visa
	 */
	public void setVisaId(long visaId);

	/**
	 * Returns the group ID of this visa.
	 *
	 * @return the group ID of this visa
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this visa.
	 *
	 * @param groupId the group ID of this visa
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this visa.
	 *
	 * @return the company ID of this visa
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this visa.
	 *
	 * @param companyId the company ID of this visa
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this visa.
	 *
	 * @return the user ID of this visa
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this visa.
	 *
	 * @param userId the user ID of this visa
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this visa.
	 *
	 * @return the user uuid of this visa
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this visa.
	 *
	 * @param userUuid the user uuid of this visa
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this visa.
	 *
	 * @return the user name of this visa
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this visa.
	 *
	 * @param userName the user name of this visa
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this visa.
	 *
	 * @return the create date of this visa
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this visa.
	 *
	 * @param createDate the create date of this visa
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this visa.
	 *
	 * @return the modified date of this visa
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visa.
	 *
	 * @param modifiedDate the modified date of this visa
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this visa.
	 *
	 * @return the modified by of this visa
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this visa.
	 *
	 * @param modifiedBy the modified by of this visa
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the cin of this visa.
	 *
	 * @return the cin of this visa
	 */
	@AutoEscape
	public String getCin();

	/**
	 * Sets the cin of this visa.
	 *
	 * @param cin the cin of this visa
	 */
	public void setCin(String cin);

	/**
	 * Returns the passport of this visa.
	 *
	 * @return the passport of this visa
	 */
	@AutoEscape
	public String getPassport();

	/**
	 * Sets the passport of this visa.
	 *
	 * @param passport the passport of this visa
	 */
	public void setPassport(String passport);

	/**
	 * Returns the nom of this visa.
	 *
	 * @return the nom of this visa
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this visa.
	 *
	 * @param nom the nom of this visa
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenom of this visa.
	 *
	 * @return the prenom of this visa
	 */
	@AutoEscape
	public String getPrenom();

	/**
	 * Sets the prenom of this visa.
	 *
	 * @param prenom the prenom of this visa
	 */
	public void setPrenom(String prenom);

	/**
	 * Returns the date naissance of this visa.
	 *
	 * @return the date naissance of this visa
	 */
	public Date getDateNaissance();

	/**
	 * Sets the date naissance of this visa.
	 *
	 * @param dateNaissance the date naissance of this visa
	 */
	public void setDateNaissance(Date dateNaissance);

	/**
	 * Returns the motif voyage of this visa.
	 *
	 * @return the motif voyage of this visa
	 */
	@AutoEscape
	public String getMotifVoyage();

	/**
	 * Sets the motif voyage of this visa.
	 *
	 * @param motifVoyage the motif voyage of this visa
	 */
	public void setMotifVoyage(String motifVoyage);

	/**
	 * Returns the date voyage of this visa.
	 *
	 * @return the date voyage of this visa
	 */
	public Date getDateVoyage();

	/**
	 * Sets the date voyage of this visa.
	 *
	 * @param dateVoyage the date voyage of this visa
	 */
	public void setDateVoyage(Date dateVoyage);

	/**
	 * Returns the duree voyage of this visa.
	 *
	 * @return the duree voyage of this visa
	 */
	public int getDureeVoyage();

	/**
	 * Sets the duree voyage of this visa.
	 *
	 * @param dureeVoyage the duree voyage of this visa
	 */
	public void setDureeVoyage(int dureeVoyage);

	/**
	 * Returns the etat of this visa.
	 *
	 * @return the etat of this visa
	 */
	public int getEtat();

	/**
	 * Sets the etat of this visa.
	 *
	 * @param etat the etat of this visa
	 */
	public void setEtat(int etat);

	@Override
	public Visa cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}